spring.application.name=notification
server.port=8084
spring.cloud.function.definition=orderCreated
spring.cloud.stream.function.definition=orderCreated
spring.cloud.stream.bindings.orderCreated-in-0.destination=order.exchange
spring.cloud.stream.bindings.orderCreated-in-0.group=notification-group
spring.cloud.stream.bindings.orderCreated-in-0.content-type=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092
#spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
#spring.rabbitmq.port=${RABBITMQ_PORT:5672}
#spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
#spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
#spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:guest}
#spring.rabbitmq.ssl.enabled=false
#spring.rabbitmq.ssl.algorithm=TLSv1.2
#spring.rabbitmq.connection-timeout=30000
#rabbitmq.exchange.name=order.exchange
#rabbitmq.queue.name=order.exchange
#rabbitmq.routing.key=order.tracking
